version: '2'
services:
  app:
    image: php:7
    restart: always
    command: php -S 0.0.0.0:8000 /app/index.php
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  composer:
    image: "composer"
    command: install
    volumes:
      - .:/app
      